### ISSUE TITLE
Please verify that the package.json has a valid "main" entry

### ISSUE THREAD

**Issue by dvrfluxchat** [destroyer22719/email-cleaner#4]
**Versions**
node version:12
email-cleaner version:1.3.0
does updating to the latest version of the module solve the problem? 

**Describe the bug**
A clear and concise description of what the bug is. The more information the better

I am using nodejs 12 in firebase cloud functions. I included email-cleaner in my dependencies in package.json. but 
I get this error when using it 

Error: Cannot find module '*/functions/node_modules/email-cleaner/dist/index.js'. Please verify that the package.json has a valid "main" entry

**Comment by destroyer22719** [comment]
Hello there, I deeply apologize for this error and thank you for bringing it to my attention. Version 1.3.1 should have fixed it as there was an issue with the code not compiling my typescript.
